---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kasten-io
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: k10
      sourceRef:
        kind: HelmRepository
        name: charts.kasten.io
      version: 7.5.8
  interval: 15s  
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: k10
  valuesFrom:
    - kind: ConfigMap
      name: kasten-io-k10-7.5.8-defaults #must match the name of the default configmap we create later
  targetNamespace: kasten-io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kasten-io-app-dashboard-info
  namespace: ${releaseNamespace}
  labels:
    "kommander.d2iq.io/application": "kasten-io"
data:
  name: "Kasten K10"
  dashboardLink: "/kasten/"
  docsLink: "https://docs.kasten.io/latest/"
  # Chart version matches app version
  version: "7.5.8"
